### ISSUE TITLE
Add option to deserialize null collections as empty collections

### ISSUE THREAD

**Issue by mattlogan** [mattlogan/auto-value-firebase#12]
Since Firebase doesn't support empty collections, we should add the option to deserialize null collections as empty collections.

For example, if an `ingredients` list can be null in the DataSnapshot, this extension should have the ability to create a `Taco` with an empty list instead of a null list.

Since null values in AutoValue require the `@Nullable` annotation, I'm imagining a new annotation called `@NullAsEmpty` or something along those lines.

**Comment by renanferrari** [comment]
I think this could be solved with `TypeAdapter`. The only change needed to achieve this is to let them deal with null values, but only if their properties are not annotated with `@Nullable` (which I think should be the adapter's default behavior anyway). Optionally, the library could provide an implementation of such adapter, something like a `NullCollectionAdapter`. 

Let me know what you think.
