### ISSUE TITLE
Does not work with Cloud Firestore

### ISSUE THREAD

**Issue by cypressf** [mattlogan/auto-value-firebase#16]
Firebase Cloud Firestore is on track to replace Firebase Real Time Database. It'd be nice if this AutoValue extension could support both.

An example incompatabililty: The code that this generates cannot be used for Cloud Firestore because it uses the com.google.firebase.database.Exclude annotation, and not the com.google.firebase.firestore.Exclude annotation.

**Comment by mattlogan** [comment]
Thanks for creating this issue! I'd love to make this work. I'm not sure I can offer a timeline right now but hopefully within the next couple weeks.

Also, apologies for the late reply. I think I need to edit my github notification settings!

**Comment by mattlogan** [comment]
I've been playing with cloud firestore a bit and I've just been writing my own `toMap` and `fromMap` methods. I'm also using Kotlin so I'm a bit less incentivized to use AutoValue these days.

Sorry I can't be of more help! Feel free to contribute a pull request if this something you'd really like to see in this library.
