### ISSUE TITLE
Classes with enum values cannot be generated.

### ISSUE THREAD

**Issue by f2prateek** [mattlogan/auto-value-firebase#2]
The following auto value class: 

``` java
@AutoValue @FirebaseValue //
public abstract class Tracker {
  public enum Status {
    FOO, BAR
  }

  public abstract Status status();

  public static Tracker fromDataSnapshot(DataSnapshot dataSnapshot) {
    AutoValue_Tracker.FirebaseValue tracker =
        dataSnapshot.getValue(AutoValue_Tracker.FirebaseValue.class);
    return new AutoValue_Tracker(tracker);
  }

  public Object toFirebaseValue() {
    return new AutoValue_Tracker.FirebaseValue(this);
  }
}
```

generates:

``` java
final class AutoValue_Tracker extends $AutoValue_Tracker {
   ...

   static final class FirebaseValue {
     // AutoValue_Status does not exist.
     private AutoValue_Status.FirebaseValue status;
     ...
   }
}
```

**Comment by f2prateek** [comment]
I guess this requires more of a clarification than anything - since I'm not sure if Firebase itself supports serializing enums or not. Although could be great if the extension handled that anyway.

**Comment by f2prateek** [comment]
Date values have a similar problem too.

**Comment by f2prateek** [comment]
I think the type adapter approach in the parcelable extension might be a good solution here https://github.com/rharter/auto-value-parcel#typeadapters.

**Comment by mattlogan** [comment]
Firebase doesn't support serializing enums, but this would still be a cool addition to the library that a lot of people might find useful.

I agree that the `TypeAdapter` approach is probably the best way to go about this. This seems pretty tricky to implement, but I might try it out soon.

Thanks for the suggestion! I'll leave this open for now.

**Comment by f2prateek** [comment]
Cool! I'm happy to try to take a stab at it over the weekend if you can't around to it.
