### ISSUE TITLE
Add support for timestamp fields

### ISSUE THREAD

**Issue by ghost** [mattlogan/auto-value-firebase#3]
Refer: http://stackoverflow.com/questions/33096128/when-making-a-pojo-in-firebase-can-you-use-servervalue-timestamp

**Comment by mattlogan** [comment]
This use case totally makes sense, and I think this extension might be able to handle it pretty well.

I'll have to look at this a bit more before I can offer a concrete plan. I'll leave this issue open for now.

**Comment by mattlogan** [comment]
After reading a bit more about ServerValue.TIMESTAMP, I'm not quite sure what you'd like to see from this library.

Can you give a suggestion for what you'd like your AutoValue class to look like so that I can understand how this might be implemented?

**Comment by mattlogan** [comment]
Closing this for now. If this garners significant interest in the future, we can reopen it.
