### ISSUE TITLE
ServerValue.TIMESTAMP support

### ISSUE THREAD

**Issue by chetbox** [mattlogan/auto-value-firebase#6]
How do I use `ServerValue.TIMESTAMP`?

`ServerValue.TIMESTAMP` has a type signature of `Map<String, String>`, but when saved it we should read it as a `Long`.

Is it possible to create a type that can be saved as `Map<String, String>`but read as `Long`?

**Comment by mattlogan** [comment]
This will be possible with type adapters!

It's in progress on this fork: https://github.com/burntcookie90/auto-value-firebase

**Comment by chetbox** [comment]
Nice! Very much looking forward to this.

Is there a workaround for now? I can't work out how to make a POJO that will wrap up a `ServerValue.TIMESTAMP` and a `Long` as appropriate.

**Comment by mattlogan** [comment]
Type adapters are included in 1.0.1. Let me know if this works for you! If not, please give me a bit more context on what you'd like to see.

**Comment by chetbox** [comment]
I found a pretty neat solution with type adapters:

``` java
public class Timestamp {

    public static class Adapter implements TypeAdapter<Timestamp, Object> {

        @Override
        public Timestamp fromFirebaseValue(Object value) {
            return new Timestamp(value); // value is a Long
        }

        @Override
        public Object toFirebaseValue(Timestamp value) {
            return value.mValue;
        }

    }

    public static Timestamp now() {
        return new Timestamp(ServerValue.TIMESTAMP);
    }

    public static Timestamp create(Long value) {
        return new Timestamp(value);
    }

    private final Object mValue;

    private Timestamp(Object value) {
        mValue = value;
    }

    public Long value() {
        return (Long) mValue;
    }

}
```

Then I can use it like so:

``` java
@AutoValue
@FirebaseValue
public abstract class MyType {

  public @FirebaseAdapter(Timestamp.Adapter.class) abstract Timestamp saved();

  public static MyType createNew() {
    return new AutoValue_MyType(Timestamp.now());
  }

  public static MyType createExisting(long saved) {
    return new AutoValue_MyType(Timestamp.create(saved));
  }

}
```

Given that server timestamps are Firebase feature it might be nice to include this in auto-value-firebase?

**Comment by mattlogan** [comment]
@chetbox Closing this for now since I'm not sure how this library would serve this need. Let me know if you have an API proposal for adding firebase timestamps to this library.
